let globalScores=[]; let personalScores=[]; let modalShowingGlobal=true; let lastStatus={ offline:false, error:false };
let resultsShowingGlobal=false;
function hasSupabase(){ return typeof window.supabase!=='undefined' && typeof window.SUPABASE_URL==='string' && typeof window.SUPABASE_ANON_KEY==='string'; }
function createClient(){ if(!hasSupabase()) return null; try{ return window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY); }catch(e){ return null; } }
function visitor(){ return window.visitorId || ''; }
export async function initializeHighScores(){ if(!visitor()) return; try{ const c=createClient(); if(!c) return; const { data, error } = await c.from('visitors').select('visitor_id').eq('visitor_id', visitor()).single(); if(error && error.code==='PGRST116'){ await c.from('visitors').insert([{ visitor_id: visitor(), created_at: new Date().toISOString() }]); } }catch(e){} }
export async function saveHighScore(ms){ if(ms<=0) return; const us = Math.round(ms*1000); const c=createClient(); if(c && visitor()){ try{ await c.from('high_scores').insert([{ visitor_id: visitor(), game_name: 'track-dash', score: us, created_at: new Date().toISOString() }]); }catch(e){} } const key='track-dash:personal-scores'; const raw=JSON.parse(localStorage.getItem(key)||'[]'); const normalized=raw.map(r=>({ timeUs: (typeof r.timeUs==='number'? r.timeUs : (typeof r.timeMs==='number'? Math.round(r.timeMs*1000) : 0)), createdAt: r.createdAt||Date.now() })).filter(r=>r.timeUs>0); normalized.push({ timeUs: us, createdAt: Date.now() }); normalized.sort((a,b)=>a.timeUs-b.timeUs); localStorage.setItem(key, JSON.stringify(normalized.slice(0,50))); }
async function loadAll(){ const c=createClient(); if(!c || !visitor()){ lastStatus.offline=true; lastStatus.error=false; personalScores=[]; globalScores=[]; return; } try{ const { data: personalData } = await c.from('high_scores').select('score, created_at').eq('visitor_id', visitor()).eq('game_name','track-dash').order('score',{ ascending:true }).limit(10); const { data: globalData } = await c.from('high_scores').select('score, created_at').eq('game_name','track-dash').order('score',{ ascending:true }).limit(10); personalScores = (personalData||[]).map(r=>({ score: normalizeToUs(r.score), created_at: r.created_at })); globalScores = (globalData||[]).map(r=>({ score: normalizeToUs(r.score), created_at: r.created_at })); lastStatus.offline=false; lastStatus.error=false; }catch(e){ lastStatus.error=true; lastStatus.offline=false; personalScores=[]; globalScores=[]; } }
function normalizeToUs(v){ const n=Number(v)||0; if(n<=0) return 0; if(n<1000) return n*10000; if(n<10000) return n*1000; return n; }
function scoreToSeconds(v){ const us=normalizeToUs(v); return us/1000000; }
function renderModalHighScores(scores){ const container=document.getElementById('modal-scores-content'); if(!container) return; const banner=document.createElement('div'); const showOffline=lastStatus.offline; const showError=lastStatus.error; if(showOffline || showError){ banner.className=showOffline? 'mb-2 px-3 py-2 rounded bg-yellow-100 text-yellow-700 text-xs' : 'mb-2 px-3 py-2 rounded bg-red-100 text-red-700 text-xs'; banner.textContent=showOffline? (modalShowingGlobal? 'Global scores unavailable offline' : 'Offline mode: showing local scores') : 'Scores temporarily unavailable'; } const table=document.createElement('table'); table.className='scores-table w-full rounded-lg overflow-hidden border-2 border-gray-300'; table.innerHTML = `<thead><tr><th class="px-3 py-2 bg-blue-500 text-white font-bold text-sm">Rank</th><th class="px-3 py-2 bg-blue-500 text-white font-bold text-sm">Score</th></tr></thead><tbody>${(scores||[]).map((s,i)=>{ const t=scoreToSeconds(s.score).toFixed(2); const rc=i<3?'text-yellow-600 font-bold bg-yellow-50':''; return `<tr class="odd:bg-gray-50 even:bg-white ${rc}"><td class="px-3 py-2 text-center border-b">${i+1}</td><td class="px-3 py-2 text-center border-b">${t}s</td></tr>`; }).join('')}</tbody>`; container.innerHTML=''; if(showOffline || showError) container.appendChild(banner); if(!scores || !scores.length){ const empty=document.createElement('div'); empty.className='text-center text-gray-500 italic py-4'; empty.textContent='No scores yet!'; container.appendChild(empty); return; } container.appendChild(table); }
export async function showHighScoresModal(){ const modal=document.getElementById('highscores-modal'); if(!modal) return; modal.classList.remove('hidden'); await loadAll(); let scores=[]; if(lastStatus.offline){ scores = modalShowingGlobal ? [] : getLocalPersonalScores(); } else { scores = modalShowingGlobal ? globalScores : personalScores; } renderModalHighScores(scores); const title=document.getElementById('modal-scores-title'); const toggle=document.getElementById('modal-toggle-scores'); if(modalShowingGlobal){ if(title) title.textContent='Global Best Times'; if(toggle){ toggle.textContent='My Best Times'; toggle.className='px-3 py-1 text-xs sm:text-sm font-bold rounded-full bg-blue-500 text-white'; } } else { if(title) title.textContent='My Best Times'; if(toggle){ toggle.textContent='Global Best Times'; toggle.className='px-3 py-1 text-xs sm:text-sm font-bold rounded-full bg-blue-600 text-white shadow'; } } }
export function closeHighScoresModal(){ const modal=document.getElementById('highscores-modal'); if(modal) modal.classList.add('hidden'); }
export function toggleModalScoreView(){ modalShowingGlobal=!modalShowingGlobal; showHighScoresModal(); }
export async function loadPanelScores(type){ const c=createClient(); if(type==='personal'){ if(!c || !visitor()){ return getLocalPersonalScores(); } await loadAll(); return personalScores; } await loadAll(); return globalScores; }
export async function loadHighScores(type){ return loadPanelScores(type); }
export function renderHighScores(scores){ const container=document.getElementById('scores-list'); if(!container) return; if(!scores||!scores.length){ container.innerHTML='<div class="text-center text-gray-500 italic py-2">No scores yet</div>'; return; } const table=document.createElement('table'); table.className='scores-table w-full rounded-lg overflow-hidden border-2 border-gray-300'; table.innerHTML=`<thead><tr><th class="px-3 py-2 bg-blue-500 text-white font-bold text-sm">Rank</th><th class="px-3 py-2 bg-blue-500 text-white font-bold text-sm">Score</th></tr></thead><tbody>${scores.map((s,i)=>{ const t=scoreToSeconds(s.score).toFixed(2); const rc=i<3?'text-yellow-600 font-bold bg-yellow-50':''; return `<tr class="odd:bg-gray-50 even:bg-white ${rc}"><td class="px-3 py-2 text-center border-b">${i+1}</td><td class="px-3 py-2 text-center border-b">${t}s</td></tr>`; }).join('')}</tbody>`; container.innerHTML=''; container.appendChild(table); }
export function renderScoresInto(containerId, scores){ const container=document.getElementById(containerId); if(!container) return; if(!scores||!scores.length){ container.innerHTML='<div class="text-center text-gray-500 italic py-2">No scores yet</div>'; return; } const heading=document.createElement('div'); heading.className='text-center text-[#2f3b58] font-bold mb-2'; heading.textContent='Best Times'; const table=document.createElement('table'); table.className='scores-table w-full rounded-lg overflow-hidden border-2 border-gray-300'; table.innerHTML=`<thead><tr><th class="px-3 py-2 bg-blue-500 text-white font-bold text-sm">Rank</th><th class="px-3 py-2 bg-blue-500 text-white font-bold text-sm">Score</th></tr></thead><tbody>${scores.map((s,i)=>{ const t=scoreToSeconds(s.score).toFixed(2); const rc=i<3?'text-yellow-600 font-bold bg-yellow-50':''; return `<tr class="odd:bg-gray-50 even:bg-white ${rc}"><td class="px-3 py-2 text-center border-b">${i+1}</td><td class="px-3 py-2 text-center border-b">${t}s</td></tr>`; }).join('')}</tbody>`; container.innerHTML=''; container.appendChild(heading); container.appendChild(table); }
export async function renderResultsBestTimes(){ const container=document.getElementById('results-best-scores'); if(!container) return; let scores=[]; let bannerText=''; let bannerClass='mb-2 px-2 py-2 rounded bg-yellow-100 text-yellow-700 text-[10px]'; const c=createClient(); const vis=visitor(); if(!c || !vis){ if(!resultsShowingGlobal){ scores=getLocalPersonalScores(); bannerText='Offline: local times'; } else { scores=[]; bannerText='Global unavailable offline'; } } else { await loadAll(); scores=resultsShowingGlobal?globalScores:personalScores; if(lastStatus.error){ bannerText='Scores temporarily unavailable'; bannerClass='mb-2 px-2 py-2 rounded bg-red-100 text-red-700 text-[10px]'; } }
 scores = (scores || []).slice(0,3); const scopeLabel=resultsShowingGlobal?'Global':'Personal'; const header=document.createElement('div'); header.className='flex items-center justify-between mb-2 gap-2'; const left=document.createElement('div'); left.className='text-[#2f3b58] font-bold text-xs sm:text-sm'; left.textContent='Best Times'; const btn=document.createElement('button'); btn.id='results-toggle-scores'; btn.className='px-2 py-1 text-[10px] sm:text-xs font-bold rounded bg-blue-600 text-white'; btn.textContent=scopeLabel; const banner=(bannerText? document.createElement('div') : null); if(banner){ banner.className=bannerClass; banner.textContent=bannerText; }
 const table=document.createElement('table'); table.className='w-full text-xs sm:text-sm border-separate border-spacing-0'; table.innerHTML=`<thead><tr><th class="text-left text-[#2f3b58] pb-1 font-bold">Rank</th><th class="text-right text-[#2f3b58] pb-1 font-bold">Time</th></tr></thead><tbody>${scores.map((s,i)=>{ const t=scoreToSeconds(s.score).toFixed(2); return `<tr><td class="py-1.5 border-t border-slate-200 text-[#2f3b58]">${i+1}</td><td class="py-1.5 border-t border-slate-200 text-right text-[#2f3b58] font-bold">${t}s</td></tr>`; }).join('')}</tbody>`; container.innerHTML=''; header.appendChild(left); header.appendChild(btn); container.appendChild(header); if(banner) container.appendChild(banner); if(!scores.length){ const empty=document.createElement('div'); empty.className='text-center text-gray-500 italic py-2 text-xs'; empty.textContent='No times yet'; container.appendChild(empty); return; } container.appendChild(table); }
export function toggleResultsScoreView(){ resultsShowingGlobal=!resultsShowingGlobal; renderResultsBestTimes(); }
function getLocalPersonalScores(){ const key='track-dash:personal-scores'; const raw=JSON.parse(localStorage.getItem(key)||'[]'); const normalized=raw.map(r=>({ score: (typeof r.timeUs==='number'? r.timeUs : (typeof r.timeMs==='number'? Math.round(r.timeMs*1000) : 0)) })).filter(r=>r.score>0); normalized.sort((a,b)=>a.score-b.score); return normalized.slice(0,10); }
